[mgr]
  prepend_keymap = [
{ on = "f", run = "plugin smart-filter", desc = "Smart filter" },
{ on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
{ on = "M", run = "plugin mount", desc = "Mount device" },

{ on = "`", run = "cd /run/media/" },
{ on = "=", run = "cd $HOME" },
]
